# Generated by Django 5.1.5 on 2025-02-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
